// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiplomaProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250523133853_Update_VideoAnalysis")]
    partial class Update_VideoAnalysis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiplomaProject.DAL.Models.Experiment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExperimentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Experiments");
                });

            modelBuilder.Entity("DiplomaProject.DAL.Models.ExperimentParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExperimentId")
                        .HasColumnType("integer");

                    b.Property<double>("Pressure")
                        .HasColumnType("double precision");

                    b.Property<double>("Radius")
                        .HasColumnType("double precision");

                    b.Property<double>("RefractiveIndex")
                        .HasColumnType("double precision");

                    b.Property<double>("Wavelength")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId")
                        .IsUnique();

                    b.ToTable("ExperimentParameters");
                });

            modelBuilder.Entity("DiplomaProject.DAL.Models.ExperimentResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CalculationData")
                        .HasColumnType("text");

                    b.Property<int>("ExperimentId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRingCount")
                        .HasColumnType("integer");

                    b.Property<string>("RingPatternImage")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId")
                        .IsUnique();

                    b.ToTable("ExperimentResults");
                });

            modelBuilder.Entity("DiplomaProject.DAL.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("DiplomaProject.DAL.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExperimentId")
                        .HasColumnType("integer");

                    b.Property<string>("ReportText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId")
                        .IsUnique();

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("DiplomaProject.DAL.Models.RingRadius", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("RadiusCm")
                        .HasColumnType("real");

                    b.Property<int>("VideoAnalysisId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VideoAnalysisId");

                    b.ToTable("RingsRadiuses");
                });

            modelBuilder.Entity("DiplomaProject.DAL.Models.StudentAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExperimentId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId");

                    b.HasIndex("QuestionId");

                    b.ToTable("StudentAnswers");
                });

            modelBuilder.Entity("DiplomaProject.DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DiplomaProject.DAL.Models.VideoAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("CentreX")
                        .HasColumnType("real");

                    b.Property<float>("CentreY")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtractedFramePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("PixelsPerCm")
                        .HasColumnType("real");

                    b.Property<string>("VideoFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VideoAnalyses");
                });

            modelBuilder.Entity("DiplomaProject.DAL.Models.Experiment", b =>
                {
                    b.HasOne("DiplomaProject.DAL.Models.User", "User")
                        .WithMany("Experiments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiplomaProject.DAL.Models.ExperimentParameters", b =>
                {
                    b.HasOne("DiplomaProject.DAL.Models.Experiment", "Experiment")
                        .WithOne("Parameters")
                        .HasForeignKey("DiplomaProject.DAL.Models.ExperimentParameters", "ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("DiplomaProject.DAL.Models.ExperimentResult", b =>
                {
                    b.HasOne("DiplomaProject.DAL.Models.Experiment", "Experiment")
                        .WithOne("Result")
                        .HasForeignKey("DiplomaProject.DAL.Models.ExperimentResult", "ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("DiplomaProject.DAL.Models.Report", b =>
                {
                    b.HasOne("DiplomaProject.DAL.Models.Experiment", "Experiment")
                        .WithOne("Report")
                        .HasForeignKey("DiplomaProject.DAL.Models.Report", "ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("DiplomaProject.DAL.Models.RingRadius", b =>
                {
                    b.HasOne("DiplomaProject.DAL.Models.VideoAnalysis", "VideoAnalysis")
                        .WithMany("Radii")
                        .HasForeignKey("VideoAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoAnalysis");
                });

            modelBuilder.Entity("DiplomaProject.DAL.Models.StudentAnswer", b =>
                {
                    b.HasOne("DiplomaProject.DAL.Models.Experiment", "Experiment")
                        .WithMany("Answers")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaProject.DAL.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("DiplomaProject.DAL.Models.Experiment", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Parameters");

                    b.Navigation("Report");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("DiplomaProject.DAL.Models.User", b =>
                {
                    b.Navigation("Experiments");
                });

            modelBuilder.Entity("DiplomaProject.DAL.Models.VideoAnalysis", b =>
                {
                    b.Navigation("Radii");
                });
#pragma warning restore 612, 618
        }
    }
}
